language: python

python:
  - "2.7"
before_install:
  - sudo apt-get install -y libevent-dev
  - sudo apt-get install -y python-dev
  - sudo easy_install -U pip
  - mkdir -p shippable/testresults shippable/codecoverage
  - sudo apt-get install -y libevent-dev
 #- sudo apt-get install libxml2-dev
 #- sudo apt-get install libxslt1-dev 
 #- sudo apt-get build-dep -y python-psycopg2
  - sudo apt-get install -y postgresql redis-server python-pip libpq-dev libxml2-dev libxslt-dev
  #- sudo pip install -r requirements_dev.txt --use-mirrors

install: "pip install -r requirements_dev.txt --use-mirrors"

script: nosetests iati_datastore
